### ISSUE TITLE
Impossible to open the website

### ISSUE THREAD

**Issue by bluenor** [LHammonds/ark-bash#1]
When I try to enter the site where the documentation should be, the site does not open, I don't know if it is a temporary problem or not working at all. I hope this comment is also useful to others because without the documentation it is impossible for most people to understand how it works.

**Comment by LHammonds** [comment]
Yes, I'm sorry about this.  I lost my job for a while and had to shut it down until I can afford a new host.  It will come back.

**EDIT:** It is painful to me not having all my articles at my fingertips or able to add to them.

**Comment by LHammonds** [comment]
Found a way you can view the articles by using archive.org.  They have a snapshot of my site as it was in March 2023.

https://web.archive.org/web/20230127211451/https://hammondslegacy.com/forum/viewforum.php?f=40

**Comment by bluenor** [comment]
Thank you Mr.
